name: Build All

on: [push]

jobs:

# For now, build for only 2.11
#  build_scala2_10:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Build for Scala 2.10
#        run: .github/workflows/sbt-build-simple.sh 2.10.7

  build_scala2_11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build for Scala 2.11
        run: .github/workflows/sbt-build-simple.sh 2.11.12

#  build_scala2_12:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Build for Scala 2.12
#        run: .github/workflows/sbt-build-simple.sh 2.12.10
#
#  build_scala2_13:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Build for Scala 2.13
#        env:
#          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#        run: .github/workflows/sbt-build.sh 2.13.0
