name: Build All

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { version: "2.12.12", binary-version: "2.12", java-version: "11" }

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.scala.java-version }}

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-coursier-scala-${{ matrix.scala.binary-version }}-

      - name: Cache Ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-scala-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-ivy-scala-${{ matrix.scala.binary-version }}-

      - name: Build core for Scala ${{ matrix.scala.version }}
        run: .github/workflows/sbt-build-simple.sh core ${{ matrix.scala.version }}

      - name: Build cli for ${{ matrix.scala.version }}
        run: .github/workflows/sbt-build-simple.sh cli ${{ matrix.scala.version }}

  build_scala2_13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-2_13-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-coursier-scala-2_13-

      - name: Cache Ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-scala-2_13-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-ivy-scala-2_13-

      - name: Build for Scala 2.13
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: .github/workflows/sbt-build.sh 2.13.4

      - name: Build cli
        run: |
          sbt \
            -J-Xmx2048m \
            "project cli" \
            ++2.13.4! \
            clean \
            universal:packageBin \
            universal:packageZipTarball \
            debian:packageBin
          ls -ld cli/target/maven2sbt-cli*
          ls -ld cli/target/universal/maven2sbt-cli*
