name: Build All

on: [push]

jobs:

  build_scala2_10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-2_10-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-coursier-scala-2_10-

      - name: Cache Ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-scala-2_10-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-ivy-scala-2_10-

      - name: Build core for Scala 2.10
        run: .github/workflows/sbt-build-simple.sh core 2.10.7

  build_scala2_11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-2_11-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-coursier-scala-2_11-

      - name: Cache Ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-scala-2_11-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-ivy-scala-2_11-

      - name: Build core for Scala 2.11
        run: .github/workflows/sbt-build-simple.sh core 2.11.12

      - name: Build cli for Scala 2.11
        run: .github/workflows/sbt-build-simple.sh cli 2.11.12

  build_scala2_12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-2_12-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-coursier-scala-2_12-

      - name: Cache Ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-scala-2_12-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-ivy-scala-2_12-

      - name: Build core for Scala 2.12
        run: .github/workflows/sbt-build-simple.sh core 2.12.10

      - name: Build cli for Scala 2.12
        run: .github/workflows/sbt-build-simple.sh cli 2.12.10

  build_scala2_13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-2_13-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-coursier-scala-2_13-

      - name: Cache Ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-scala-2_13-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-ivy-scala-2_13-

      - name: Build for Scala 2.13
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: .github/workflows/sbt-build.sh 2.13.1
