name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: sbt GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
      run: |
        echo "Run] sbt GitHub release"
        echo 'sbt -J-Xmx2048m "; project core; clean; +test; +packagedArtifacts"'
        sbt -J-Xmx2048m "; project core; clean; +test; +packagedArtifacts"
        echo 'sbt -J-Xmx2048m "; project cli; ++2.13.1!; clean; universal:packageBin; universal:packageZipTarball; debian:packageBin"'
        sbt -J-Xmx2048m "; project cli; ++2.13.1!; clean; universal:packageBin; universal:packageZipTarball; debian:packageBin"
        echo 'sbt -J-Xmx2048m "; gitHubRelease"'
        sbt -J-Xmx2048m "; gitHubRelease"
    - name: sbt Publish core
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
      run: |
        echo "Run] sbt publish"
        echo 'sbt -J-Xmx2048m "; project core; clean; +publish"'
        sbt -J-Xmx2048m "; project core; clean; +publish"
    - name: Sync core to Maven Central
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
      run: |
        PROJECT_VERSION="${GITHUB_REF#refs/tags/v}"
        BINTRAY_SUBJECT=kevinlee
        BINTRAY_REPO=maven
        BINTRAY_PACKAGE=maven2sbt-core
        echo "BINTRAY_SUBJECT: $BINTRAY_SUBJECT"
        echo "   BINTRAY_REPO: $BINTRAY_REPO"
        echo "BINTRAY_PACKAGE: $BINTRAY_PACKAGE"
        echo "PROJECT_VERSION: $PROJECT_VERSION"
        echo "Sync to Maven Central..."
        curl --user $BINTRAY_USER:$BINTRAY_PASS -X POST "https://api.bintray.com/maven_central_sync/$BINTRAY_SUBJECT/$BINTRAY_REPO/$BINTRAY_PACKAGE/versions/$PROJECT_VERSION"
