name: Release

on:
  push:
    tags:
      - '*'

env:
  CLI_SCALA_VERSION: "3.0.0-RC1"
  CLI_SCALA_BINARY_VERSION: "3.0.0-RC1"
  GRAALVM_VERSION: "21.0.0.2"
  GRAALVM_JAVA_VERSION: "java11"
  GRAALVM_ARCH: "amd64"
  GRAALVM_BIN_DIR_NAME: "native-image"

jobs:
  github-release:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-

      - name: sbt GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
        run: |
          echo "Run] sbt GitHub release"
          echo 'sbt -J-Xmx2048m devOopsGitHubRelease'
          sbt \
            -J-Xmx2048m \
            devOopsGitHubRelease

  github-release-artifacts-and-publish:
    needs: github-release

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { name: "Scala 2", version: "2.12.12",   binary-version: "2.12",      java-version: "11", cli: "" }
          - { name: "Scala 2", version: "2.13.3",    binary-version: "2.13",      java-version: "11", cli: "" }
          - { name: "Scala 3", version: "3.0.0-RC1", binary-version: "3.0.0-RC1", java-version: "11", cli: "cli" }

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.scala.java-version }}

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-

      - name: "sbt GitHub Release and Publish tag for ${{ matrix.scala.name }} ${{ matrix.scala.version }} - ${{ github.run_number }}"
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: |
          export GITHUB_TAG=${GITHUB_REF#refs/tags/}
          .github/workflows/sbt-release.sh ${{ matrix.scala.version }} ${{ matrix.scala.cli }}

  graalvm-gh-release:
    needs: github-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        run-binary: [maven2sbt-cli]
    steps:

      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "graalvm-ce-java11@"
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ env.CLI_SCALA_BINARY_VERSION }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ env.CLI_SCALA_BINARY_VERSION }}-

      - name: "GraalVM Build for Scala ${{ env.CLI_SCALA_VERSION }} - ${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
          CURRENT_BRANCH_NAME: ${{ github.ref }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
        run: |
          ./sbt \
            -J-Xmx2048m \
            ++${{ env.CLI_SCALA_VERSION }}! \
            clean \
            test \
            nativeImage

          rm -f */target/scala-*/maven2sbt*.jar

          ls -lGh cli/target/${{ env.GRAALVM_BIN_DIR_NAME }}/
          sh -c "cli/target/${{ env.GRAALVM_BIN_DIR_NAME }}/${{ matrix.run-binary }} --help"

          mv cli/target/${{ env.GRAALVM_BIN_DIR_NAME }}/${{ matrix.run-binary }} cli/target/${{ env.GRAALVM_BIN_DIR_NAME }}/${{ matrix.run-binary }}-${{ matrix.os }}

          ./sbt \
            -J-Xmx2048m \
            devOopsGitHubReleaseUploadArtifacts

  graalvm-win-gh-release:
    needs: github-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        run-binary: [maven2sbt-cli]
        run-binary-ext: [exe]
    steps:
      - name: Configure git
        run: "git config --global core.autocrlf false"
        shell: bash
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "graalvm-ce-java11@"
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ env.CLI_SCALA_BINARY_VERSION }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ env.CLI_SCALA_BINARY_VERSION }}-

      - name: "GraalVM Build for Scala ${{ env.CLI_SCALA_VERSION }} - ${{ github.run_number }}"
        shell: bash
        env:
          CURRENT_BRANCH_NAME: ${{ github.ref }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
        run: |
          sbt \
            -J-Xmx2048m \
            ++${{ env.CLI_SCALA_VERSION }}! \
            clean \
            test \
            nativeImage

          rm -f */target/scala-*/maven2sbt*.jar

          ls -lGh cli/target/${{ env.GRAALVM_BIN_DIR_NAME }}/
          sh -c "cli/target/${{ env.GRAALVM_BIN_DIR_NAME }}/${{ matrix.run-binary }} --help"

          mv cli/target/${{ env.GRAALVM_BIN_DIR_NAME }}/${{ matrix.run-binary }}.${{ matrix.run-binary-ext }} cli/target/${{ env.GRAALVM_BIN_DIR_NAME }}/${{ matrix.run-binary }}-${{ matrix.os }}.${{ matrix.run-binary-ext }}

          sbt \
            -J-Xmx2048m \
            devOopsGitHubReleaseUploadArtifacts


  publish_maven:
    needs: github-release-artifacts-and-publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync core to Maven Central
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: |
          PROJECT_VERSION="${GITHUB_REF#refs/tags/v}"
          BINTRAY_SUBJECT=kevinlee
          BINTRAY_REPO=maven
          BINTRAY_PACKAGE=maven2sbt-core
          echo "BINTRAY_SUBJECT: $BINTRAY_SUBJECT"
          echo "   BINTRAY_REPO: $BINTRAY_REPO"
          echo "BINTRAY_PACKAGE: $BINTRAY_PACKAGE"
          echo "PROJECT_VERSION: $PROJECT_VERSION"
          echo "Sync to Maven Central..."
          curl --user $BINTRAY_USER:$BINTRAY_PASS -X POST "https://api.bintray.com/maven_central_sync/$BINTRAY_SUBJECT/$BINTRAY_REPO/$BINTRAY_PACKAGE/versions/$PROJECT_VERSION"
